// AUTO_GENERATED BY JavaPoet
package src.app;

public class FlightMsg255 {
  private final int aircraftId;

  public FlightMsg255(final int aircraftId) {
    this.aircraftId = aircraftId;
  }

  public int getAircraftId() {
    return aircraftId;
  }
}
